LISTBOX_MIMETYPE = "application/x-item"

NODE_INPUT = 1
NODE_OUTPUT = 2 
NODE_INPUT_INT = 3
NODE_BUTTON_INPUT = 4
NODE_INPUT_FLOAT = 5
NODE_LIST_CREATOR = 6
NODE_DICT_CREATOR = 7


NODE_MATHEMATICS_SUM = 50
NODE_MATHEMATICS_MULTIPLICATION = 51 
NODE_MATHEMATICS_DIVISION = 52
NODE_MATHEMATICS_SUBTRACTION = 53
NODE_MATHEMATICS_PERCENTAGE = 54
NODE_MATHEMATICS_POWER = 55
NODE_MATHEMATICS_LOG = 56
NODE_MATHEMATICS_SQRT = 57
NODE_MATHEMATICS_ABS = 58
NODE_MATHEMATICS_FACTORIAL = 59
NODE_MATHEMATICS_TRIGONOMETRY = 60
NODE_MATHEMATICS_EBOB = 61
NODE_MATHEMATICS_EKOK = 62


NODE_QBROWSER = 100
NODE_QBROWSER_HEADERS_TABLE = 101
NODE_QT_PROXY_INPUT = 102

NODE_CV2_CAM_VIEWER = 200
NODE_CV2_CAM_SENDER = 201
NODE_TIMER = 202
NODE_CROP = 203
NODE_SCREEN_SENDER = 204
NODE_CV2_RESIZE = 205
MIXER_NODE = 206
IMAGE_LOADER_NODE = 207

NODE_HTTP_SERVER = 300 

NODES = {}
